r"""A wrong model with a good r-squared, on real measured data.

Nothing else in this gallery shows a model that is simply *wrong*. Every
page fits data generated by, or well described by, the shape being fitted,
so every page ends with a high :math:`r^2` that means what it appears to
mean. This one does not.

The Fe L-edge of :math:`[\text{FeCl}_4]^-` is fitted with a ladder of
increasingly elaborate models. Along that ladder :math:`r^2` climbs from
0.87 to 0.99 and AIC falls by 300 -- both scores say "better" at every
rung. A runs test on the residuals says "still the wrong model" at every
rung, with a z-score near :math:`-8` throughout. The residual carries
information the scalar scores throw away.

Data provenance
---------------
``manuscript/examples/fecl4/FeCl4_d5.txt``, measured spectra reproduced in
this repository **by permission of the original authors** and NOT covered
by its MIT licence, which applies to the code. Cite Wasinger EC, de Groot
FMF, Hedman B, Hodgson KO, Solomon EI. L-edge X-ray absorption
spectroscopy of non-heme iron sites. *J Am Chem Soc.* 2003;125(42):12894-906.
doi:10.1021/ja034634s. A third party wanting to reuse these spectra should
seek permission from those authors; see
``manuscript/examples/fecl4/ro-crate-metadata.json``.
"""

from pathlib import Path

import numpy as np
from _plotting import MUTED_COLOR, savefig
from spectrafit_core import (
    FitGraph,
    FitOptions,
    FitResult,
    MeasurementData,
    ModelNodeSpec,
    ModelType,
    Parameter,
    fit,
)

#: Repo root, resolved from this file so the script runs from any cwd.
REPO_ROOT = Path(__file__).resolve().parents[3]
SPECTRUM = REPO_ROOT / "manuscript" / "examples" / "fecl4" / "FeCl4_d5.txt"

WINDOW_EV = (704.0, 716.0)


# --8<-- [start:data]
def load_l3_window() -> tuple[np.ndarray, np.ndarray]:
    """Load the measured d5 spectrum and cut to the L3 region.

    The window spans the L3 white line at ~707.9 eV and the weaker feature
    near 713.4 eV, and stops short of the L2 edge so the comparison stays
    about one absorption region rather than the whole spectrum.
    """
    raw = np.loadtxt(SPECTRUM)
    lo, hi = WINDOW_EV
    keep = (raw[:, 0] >= lo) & (raw[:, 0] <= hi)
    return raw[keep, 0], raw[keep, 1]


x, y = load_l3_window()
# --8<-- [end:data]


# --8<-- [start:ladder]
def _peak(index: int, model_type: ModelType, amplitude: float, center: float) -> ModelNodeSpec:
    """One bounded peak component; Voigt gets its extra Lorentzian width."""
    parameters = {
        "amplitude": Parameter(value=amplitude, min=0.0),
        "center": Parameter(value=center, min=float(x.min()), max=float(x.max())),
        "sigma": Parameter(value=1.0, min=0.05, max=6.0),
    }
    if model_type is ModelType.TRUE_VOIGT:
        parameters["gamma"] = Parameter(value=0.5, min=1e-3, max=6.0)
    return ModelNodeSpec(id=f"p{index}", model_type=model_type, parameters=parameters)


def fit_ladder(x: np.ndarray, y: np.ndarray) -> dict[str, FitResult]:
    """Three models of increasing elaboration, fitted to the same window."""
    gaussian, voigt = ModelType.GAUSSIAN, ModelType.TRUE_VOIGT
    ladder = {
        "1 Gaussian": [_peak(0, gaussian, 15.0, 707.9)],
        "2 Gaussians": [_peak(0, gaussian, 15.0, 707.9), _peak(1, gaussian, 2.5, 713.4)],
        "3 Voigts": [
            _peak(0, voigt, 15.0, 707.9),
            _peak(1, voigt, 2.5, 713.4),
            _peak(2, voigt, 1.5, 710.5),
        ],
    }
    data = MeasurementData(x=x.tolist(), y=y.tolist())
    return {
        name: fit(FitGraph(nodes=nodes), data, FitOptions(solver="lm"))
        for name, nodes in ladder.items()
    }


results = fit_ladder(x, y)
# --8<-- [end:ladder]


# --8<-- [start:runs_test]
def runs_z(residuals: np.ndarray) -> tuple[int, float, float]:
    """Wald-Wolfowitz runs test on the residual signs.

    A *run* is a maximal stretch of same-signed residuals. Residuals that
    are independent noise around a correct model produce about
    ``2*n_pos*n_neg/n + 1`` runs; far fewer means the signs come in long
    stretches, i.e. the curve is systematically above the data in one place
    and below it in another. Returns ``(observed, expected, z)``.

    Caveat, stated because it changes how hard the number may be pushed:
    the test assumes independent residuals. This spectrum is oversampled
    (0.1 eV steps across the white line), so genuinely correlated
    measurement noise would also depress the run count. Read a large
    negative z as strong corroboration of what the residual panel already
    shows, not as a calibrated p-value.
    """
    signs = np.sign(residuals)
    signs = signs[signs != 0]
    n = len(signs)
    n_pos = int((signs > 0).sum())
    n_neg = n - n_pos
    observed = int((signs[1:] != signs[:-1]).sum()) + 1
    expected = 2.0 * n_pos * n_neg / n + 1.0
    variance = (expected - 1.0) * (expected - 2.0) / (n - 1.0)
    return observed, expected, (observed - expected) / np.sqrt(variance)


def report(results: dict[str, FitResult]) -> None:
    """Print the ladder, and assert the point it is here to make."""
    print(f"{'model':13s} {'r^2':>9s} {'AIC':>9s} {'runs':>6s} {'expected':>9s} {'z':>7s}")
    stats = {}
    for name, result in results.items():
        observed, expected, z = runs_z(np.array(result.residuals))
        stats[name] = (result.r_squared, result.aic, z)
        print(
            f"{name:13s} {result.r_squared:9.5f} {result.aic:9.1f} "
            f"{observed:6d} {expected:9.1f} {z:7.1f}",
        )

    r2s = [s[0] for s in stats.values()]
    aics = [s[1] for s in stats.values()]
    zs = [s[2] for s in stats.values()]

    # Both scalar scores improve monotonically down the ladder ...
    assert r2s == sorted(r2s), "r^2 should climb at every rung"
    assert aics == sorted(aics, reverse=True), "AIC should fall at every rung"
    # ... while the residuals stay structured at every rung, including the last.
    assert max(zs) < -5.0, "every rung should remain far from random residuals"
    assert results["3 Voigts"].r_squared > 0.99, "the last rung should look excellent"


report(results)
# --8<-- [end:runs_test]

if __name__ == "__main__":
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(
        2,
        3,
        figsize=(12.0, 6.0),
        sharex=True,
        gridspec_kw={"height_ratios": [2.1, 1.0]},
    )
    for column, (name, result) in enumerate(results.items()):
        observed, expected, z = runs_z(np.array(result.residuals))
        ax_fit, ax_res = axes[0][column], axes[1][column]

        ax_fit.scatter(x, y, s=14, alpha=0.5, color="#4C72B0", zorder=2)
        ax_fit.plot(x, result.best_fit, color="#C44E52", linewidth=1.9, zorder=3)
        ax_fit.set_title(f"{name}\nr² = {result.r_squared:.4f}   AIC = {result.aic:.0f}")
        if column == 0:
            ax_fit.set_ylabel("intensity (a.u.)")

        ax_res.axhline(0.0, color=MUTED_COLOR, linewidth=0.9, zorder=1)
        ax_res.plot(x, result.residuals, color="#8172B2", linewidth=1.4, zorder=2)
        ax_res.set_xlabel("photon energy (eV)")
        ax_res.set_title(
            f"residual — runs {observed} vs {expected:.0f} expected, z = {z:.1f}",
            fontsize=9,
        )
        if column == 0:
            ax_res.set_ylabel("data − fit")

    fig.suptitle(
        "Both scores say better at every rung; the residual says wrong at every rung",
        fontweight="bold",
    )
    fig.tight_layout()
    savefig(fig, "misspecified_model")
