#!/usr/bin/env python3
"""Render MANUSCRIPT.md and TODO.md from manuscript-state.json + sections/*.md.

Why this exists as a committed script. The original render was produced by a
drafting tool that was never committed, so `MANUSCRIPT.md` could not be
rebuilt from its own sources — it drifted three revisions behind
`sections/*.md` (wrong title, no case study, unresolved `[CITE:]` markers)
with nothing in the repo able to detect or fix that. For a paper whose subject
is checkable claims, a deliverable that cannot be regenerated from its inputs
is the wrong artefact to be handing a reviewer.

Usage:

    uv run python manuscript/render_manuscript.py            # write
    uv run python manuscript/render_manuscript.py --check    # CI-style diff

`--check` exits non-zero when the rendered output differs from what is on
disk, which is what makes staleness a build failure rather than something
noticed by eye months later.

Section order and headings come from the venue binding in the state file, so
retargeting the paper at a different venue is a state change, not a rewrite of
this script.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
DRAFT = HERE / "draft"
STATE = DRAFT / "manuscript-state.json"
SECTIONS = DRAFT / "sections"

# JORS software-metapaper heading order. `role` keys the section files; the
# heading is what the venue calls that role.
JORS_BINDING: list[tuple[str, str | None]] = [
    ("summary", None),  # the title — rendered as `## Title`, not a heading of its own
    ("abstract", "Abstract"),
    ("context", "Introduction"),
    ("method", "Implementation and architecture"),
    ("evidence", "Quality control"),
    ("availability", "Availability"),
    ("reuse", "Reuse potential"),
    # End matter, as real sections rather than as a submission-form checklist.
    # These previously lived in one "Submission metadata" section that opened
    # by telling the author which fields to fill in — so the paper carried
    # ADVICE about writing a funding statement instead of a funding statement,
    # and JORS requires the statement itself. The author-only questions moved
    # to manuscript/draft/AUTHOR-CHECKLIST.md, which is deliberately not
    # rendered: a submitted paper carries the answers, not the questions.
    ("acknowledgements", "Acknowledgements"),
    ("funding", "Funding statement"),
    ("competing", "Competing interests"),
    ("data_availability", "Data availability"),
]

# Rendered in the front matter directly after the abstract, per venue
# convention, rather than in the body flow above.
FRONT_MATTER_AFTER_ABSTRACT: list[tuple[str, str]] = [
    ("keywords", "Keywords"),
]

SEVERITY_ORDER = {"blocker": 0, "should-fix": 1, "informational": 2}


def git_commit() -> str:
    """Return the current HEAD sha, or a marker when git is unavailable."""
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            check=True,
            capture_output=True,
            text=True,
            cwd=HERE,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"
    return out.stdout.strip()


def _placeholders(text: str) -> list[str]:
    """Return unresolved ``{{TOKEN}}`` placeholders, in order of appearance."""
    return re.findall(r"\{\{([A-Z0-9_]+)\}\}", text)


def render_manuscript(state: dict) -> tuple[str, list[str]]:
    """Return the rendered manuscript and every unresolved placeholder in it."""
    lines: list[str] = []
    venue = state["venue"]
    add = lines.append

    add(f"# {state.get('title') or venue['id']}")
    add("")
    add(
        "Generated by `manuscript/render_manuscript.py` from `manuscript-state.json` "
        "and `sections/*.md`. Regenerated in full on every run; edit the section "
        "files, never this one.",
    )
    add("")
    add(f"- Venue: {venue['id']} ({venue['binding']})")
    add(f"- Generated at: {datetime.now(UTC).strftime('%Y-%m-%dT%H:%M:%SZ')}")
    add(f"- Repository commit: `{git_commit()}`")
    add("")

    by_role = {s["role"]: s for s in state["sections"]}
    unresolved: list[str] = []

    for role, heading in JORS_BINDING:
        section = by_role.get(role)
        if section is None:
            continue
        body = (DRAFT / section["file"]).read_text().strip()
        if not body:
            continue
        unresolved.extend(f"{role}: {{{{{token}}}}}" for token in _placeholders(body))
        if role == "summary":
            add("## Title")
            add("")
            add(body)
            add("")
            continue
        add(f"## {heading}")
        add("")
        add(body)
        add("")
        # Keywords belong immediately after the abstract in the front matter,
        # not in the body flow, so they are emitted here rather than as their
        # own entry in JORS_BINDING.
        if role == "abstract":
            for fm_role, fm_heading in FRONT_MATTER_AFTER_ABSTRACT:
                fm_section = by_role.get(fm_role)
                if fm_section is None:
                    continue
                fm_body = (DRAFT / fm_section["file"]).read_text().strip()
                if not fm_body:
                    continue
                add(f"## {fm_heading}")
                add("")
                add(fm_body)
                add("")

    figures = state.get("figures", [])
    if figures:
        add("## Figures")
        add("")
        for f in sorted(figures, key=lambda x: x["number"]):
            pending = "" if f.get("status") == "rendered" else f"  _[{f.get('status')}]_"
            add(f"**Figure {f['number']}.** {f['caption']}{pending}")
            add("")
            if f.get("alt_text"):
                add(f"_Alt text:_ {f['alt_text']}")
                add("")

    refs = state.get("references", [])
    if refs:
        add("## References")
        add("")
        # Vancouver: numbered in citation order. The section bodies cite by key
        # (`[lmfit]`), so the mapping from key to number is printed alongside —
        # substituting numbers into the prose is a submission-time step against
        # the venue's template, not something to bake in here.
        for n, r in enumerate(refs, start=1):
            add(f"{n}. {r['vancouver']}  _(cited as `[{r['key']}]`)_")
        add("")

    return "\n".join(lines).rstrip() + "\n", unresolved


def render_todo(state: dict, unresolved: list[str]) -> str:
    """Return the TODO list, regenerated from state; it carries no checkbox state."""
    todo = [t for t in state.get("todo", []) if t.get("status") != "resolved"]
    todo.sort(key=lambda t: SEVERITY_ORDER.get(t.get("severity", "informational"), 9))
    counts: dict[str, int] = {}
    for t in todo:
        counts[t.get("severity", "informational")] = (
            counts.get(t.get("severity", "informational"), 0) + 1
        )

    lines = [
        f"# Manuscript TODO — {state['venue']['id']}",
        "",
        "Generated by `manuscript/render_manuscript.py` from `manuscript-state.json`.",
        "",
        (
            "Fully regenerated on every run. It carries no checkbox state: resolve an "
            "item in the state file and its line disappears here."
        ),
        "",
        "Gates: " + " · ".join(f"{k}: {v}" for k, v in state["gates"].items()),
        "",
    ]
    if unresolved:
        lines += [
            (
                f"**{len(unresolved)} unresolved placeholder(s)** in the rendered "
                "manuscript — these are deliberate, and block only the numbers they "
                "stand in for:"
            ),
            "",
            *(f"- `{u}`" for u in unresolved),
            "",
        ]
    summary = " · ".join(f"{n} {sev}" for sev, n in sorted(counts.items()))
    lines += [f"{len(todo)} open item(s)" + (f": {summary}" if summary else ""), ""]
    for t in todo:
        owner = f" ({t['owner']})" if t.get("owner") else ""
        role = f" [{t['role']}]" if t.get("role") else ""
        lines.append(f"- **{t.get('severity', 'informational')}**{role}{owner} {t['text']}")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    """Render both artefacts, or verify they are up to date."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the rendered output differs from what is on disk",
    )
    args = ap.parse_args()

    state = json.loads(STATE.read_text())
    manuscript, unresolved = render_manuscript(state)
    todo = render_todo(state, unresolved)

    targets = {DRAFT / "MANUSCRIPT.md": manuscript, DRAFT / "TODO.md": todo}

    if args.check:
        stale = []
        for path, wanted in targets.items():
            current = path.read_text() if path.exists() else ""
            # The generated-at line moves every run; ignore it when diffing.
            norm = lambda t: [ln for ln in t.splitlines() if not ln.startswith("- Generated at:")]
            if norm(current) != norm(wanted):
                stale.append(path.name)
                sys.stdout.writelines(
                    difflib.unified_diff(
                        norm(current),
                        norm(wanted),
                        fromfile=f"{path.name} (on disk)",
                        tofile=f"{path.name} (rendered)",
                        lineterm="",
                        n=1,
                    ),
                )
                print()
        if stale:
            print(f"STALE: {', '.join(stale)} — run manuscript/render_manuscript.py")
            raise SystemExit(1)
        print("manuscript render is up to date")
        return

    for path, content in targets.items():
        path.write_text(content)
        print(f"wrote {path.relative_to(HERE.parent)} ({len(content.splitlines())} lines)")
    if unresolved:
        print(f"note: {len(unresolved)} unresolved placeholder(s): {', '.join(unresolved)}")


if __name__ == "__main__":
    main()
