"""Pytest fixtures and CLI flags scoped to ``tests/audit/``.

Plan G caveat — the OpenAPI watchdog (``test_audit_openapi_watchdog.py``) snapshots
the published schema against a checked-in golden. When an intentional schema change
lands, the golden must be regenerated by passing ``--update-golden`` so the test
rewrites the file instead of asserting against the stale snapshot.
"""

from __future__ import annotations

import pytest


@pytest.fixture
def no_runtime_l3(monkeypatch: pytest.MonkeyPatch) -> None:
    """Disable the runtime L3 claim⇒evidence guard in ``run_audit``.

    For tests that drive ``run_audit`` with a stub / minimal ``results.json`` to
    exercise a *different* concern (claim counting, gap-status rung capping,
    sidecar recompute) — those payloads intentionally omit the evidence sections
    a complete report carries. Runtime L3 itself is covered by
    ``test_claim_evidence_integrity`` (data-level) and the real-run
    ``test_audit_runner_end_to_end`` (write-time).
    """
    from oracles.audit import runner as runner_mod

    monkeypatch.setattr(
        runner_mod, "_assert_audited_claims_resolve", lambda *a, **k: None
    )


def pytest_addoption(parser: pytest.Parser) -> None:
    """Register ``--update-golden`` for the audit watchdog regeneration path."""
    parser.addoption(
        "--update-golden",
        action="store_true",
        default=False,
        help=(
            "Regenerate checked-in golden snapshots (e.g. the OpenAPI "
            "watchdog's normalised schema) instead of asserting against them."
        ),
    )
