"""Regenerate the directory-tree block in contributor-guide/architecture.md.

Wraps `rrt tree` (the MCP tool only reads an existing `.rrt/tree.lock.toml`;
it can't generate or filter one — see the CLI invocation this replaces) and
filters out top-level entries that don't belong in a reader-facing
architecture overview:

- `analysis/`, `manuscript/`, `ADR-INDEX.md` — all excluded from the GitHub
  mirror publish entirely (`pyproject.toml`'s
  `[tool.rrt.publish_targets.github].exclude`), so listing any of them here
  is actively wrong on that mirror, not just noise. `analysis/` and
  `manuscript/` survive as empty directories there (their exclude patterns
  are `analysis/*` / `manuscript/draft/*` etc., not the bare directory), so
  they still legitimately appear in the tree on both remotes — but
  `ADR-INDEX.md` is excluded as an exact file, with nothing left behind to
  list, so it must be filtered here or the regenerated tree permanently
  disagrees with the mirror's actual (stripped) filesystem.
- `test-results/`, `vibe-sessions/` — empty scratch directories (a
  Playwright run marker and a `.gitkeep` respectively), no architectural
  content.
- `DECISIONS.md`, `DECISIONS-archive.md` — an append-only ADR log and its
  frozen archive, not part of the directory *structure* this page exists to
  show. `DECISIONS.md` is already linked from `CONTRIBUTING.md`, and its own
  header points readers at `DECISIONS-archive.md` for anything older — so
  dropping both here is a visibility choice, not a broken link.

A naive full-repo dump is not the more "honest" choice here despite the
plain reading of that principle — the previous version of this fix showed
everything unfiltered, which was accurate for GitLab but actively
misleading on the GitHub mirror, where `analysis/` does not exist at all.

Uses `--format ascii` (a real `|--`/`` `-- `` box-drawing tree), not
`--format markdown`: the markdown format's 2-space nested-bullet indentation
doesn't meet most Markdown parsers' 4-space (or content-aligned) threshold
for a nested list, so every entry — regardless of actual depth — rendered
as one long flat top-level bullet list with no visible hierarchy. Wrapping
the ascii tree in a fenced code block avoids that parser dependency
entirely and reads as an actual tree, not a wall of ~100 flat bullets.

Usage: `uv run python scripts/render_architecture_tree.py` (writes the
filtered block between the `<!-- rrt:auto:start:dirtree -->` /
`<!-- rrt:auto:end:dirtree -->` markers in
`docs/contributor-guide/architecture.md`). Run `rrt tree --root . --max-depth
2 --snapshot` first (or let this script do it) to refresh `.rrt/tree.lock.toml`
before checking for drift with `rrt tree --root . --max-depth 2 --check`.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ARCHITECTURE_MD = REPO_ROOT / "docs" / "contributor-guide" / "architecture.md"
ANCHOR = "dirtree"
START_MARKER = f"<!-- rrt:auto:start:{ANCHOR} -->"
END_MARKER = f"<!-- rrt:auto:end:{ANCHOR} -->"

# Top-level entries to drop from the rendered tree — see the module
# docstring for why each one is excluded.
EXCLUDED_PATHS = (
    "analysis/",
    "manuscript/",
    "ADR-INDEX.md",
    "test-results/",
    "vibe-sessions/",
    "DECISIONS.md",
    "DECISIONS-archive.md",
    # NESTED entries, which is why this tuple is path-based rather than
    # top-level-only. Both are generated by `poe docs_build` and gitignored, so
    # they exist on a machine that has built the docs and not in CI's clean
    # checkout — making the rendered tree depend on WHETHER YOU BUILT THE DOCS
    # FIRST. That cost four red pipelines (366818, 366826, 366889, 366934).
    #
    # The first attempt at this fix added them to a filter that only ever
    # compared TOP-LEVEL entries, so `docs/performance/` — which renders as a
    # child of `docs/` — never matched and nothing changed. The local check
    # that "verified" it was vacuous: both sides of the comparison had the
    # directories on disk. Hence `_depth_and_name` below, and hence the
    # pre-push hook, so this is caught before a runner sees it.
    "docs/performance/",
    "overrides/_generated/",
)


def _run_rrt_tree() -> str:
    result = subprocess.run(
        ["rrt", "tree", "--root", ".", "--format", "ascii", "--max-depth", "2"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def _tracked_prefixes() -> set[str]:
    """Every path git tracks, plus each of its parent directories.

    `rrt tree` walks the filesystem and knows nothing about git, so anything
    sitting in a working tree lands in the rendered output — including files
    CI's clean checkout will never have. That makes the tree depend on local
    state, which is the same failure the `docs/performance/` exclusion below
    was added for; a scratch file at the repo root reproduced it exactly.
    Filtering on tracked-ness fixes the class rather than one more instance.
    """
    listing = subprocess.run(
        ["git", "ls-files"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    prefixes: set[str] = set()
    for path in listing.splitlines():
        parts = path.split("/")
        for depth in range(1, len(parts) + 1):
            prefixes.add("/".join(parts[:depth]))
    return prefixes


def _depth_and_name(line: str) -> tuple[int, str] | None:
    """Return (depth, name) for a tree line, or None if it is not one.

    `rrt tree --format ascii` indents in four-character blocks (`|   ` for a
    continuing branch, four spaces for an exhausted one) before the `|-- ` or
    `` `-- `` marker, so depth is simply how many blocks precede the marker.
    """
    i = 0
    while line[i : i + 4] in ("|   ", "`   ", "    "):
        i += 4
    if line[i : i + 4] not in ("|-- ", "`-- "):
        return None
    return i // 4, line[i + 4 :].strip()


def filter_tree(ascii_tree: str) -> str:
    """Strip rrt's CLI banner/footer and drop each excluded path and its children.

    `rrt tree` without `--inject` prints a Rich-formatted banner ("Project
    tree" header, "-> Root/Format/..." lines, a "-- Tree --" divider) and a
    "Done. N entries shown." footer around the actual tree — none of that
    belongs in the doc. Real tree lines always start with either `|` (a
    branch marker or a mid-list continuation) or `` ` `` (the last branch at
    that depth); banner/footer lines never do (they start with `✔`, `→`, the
    Unicode box-divider `─`, or are blank).
    """
    excluded = {p.rstrip("/") for p in EXCLUDED_PATHS}
    tracked = _tracked_prefixes()
    kept: list[str] = []
    stack: list[str] = []
    skip_depth: int | None = None

    for line in ascii_tree.splitlines():
        if not line or line[0] not in "|`":
            continue  # banner, footer, or divider line
        parsed = _depth_and_name(line)
        if parsed is None:
            continue
        depth, name = parsed

        # Leaving the excluded subtree once we are back at or above its depth.
        if skip_depth is not None and depth <= skip_depth:
            skip_depth = None

        del stack[depth:]
        stack.append(name.rstrip("/"))

        joined = "/".join(stack)
        if skip_depth is None and (joined in excluded or joined not in tracked):
            skip_depth = depth
        if skip_depth is None:
            kept.append(line)
    return "```text\n" + "\n".join(kept) + "\n```"


def splice(architecture_text: str, filtered_tree: str) -> str:
    """Replace the anchored block in `architecture_text` with `filtered_tree`."""
    start_idx = architecture_text.index(START_MARKER) + len(START_MARKER)
    end_idx = architecture_text.index(END_MARKER)
    return architecture_text[:start_idx] + "\n" + filtered_tree + "\n" + architecture_text[end_idx:]


def main() -> int:
    """Regenerate and write the filtered directory tree into architecture.md."""
    raw_tree = _run_rrt_tree()
    filtered = filter_tree(raw_tree)
    architecture_text = ARCHITECTURE_MD.read_text(encoding="utf-8")
    updated = splice(architecture_text, filtered)
    ARCHITECTURE_MD.write_text(updated, encoding="utf-8")
    print(
        f"wrote filtered tree ({len(filtered.splitlines())} lines) into {ARCHITECTURE_MD}",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
