/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available benchmark run ids (newest first).
         * @description Return the run ids under ``<REPORTS_ROOT>/benchmark/`` (newest first).
         */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The latest run's report (the BenchReport contract).
         * @description Return the newest run's validated :class:`BenchReport`.
         */
        get: operations["get_latest_report_api_v1_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/report/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A specific run's report by id.
         * @description Return the validated :class:`BenchReport` for the given *run_id*.
         */
        get: operations["get_report_api_v1_report__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The latest run's verification ledger (trust block + inference).
         * @description Latest run's verification ledger slice (trust block + inference).
         *
         *     The downloadable 'verification ledger' the UI links to for reviewers. The full
         *     V&V detail (wires, NIST datasets, nested-adequacy, σ-calibration, speed-significance)
         *     lives here rather than as a dedicated UI page; the landing carries only a compact,
         *     externally-anchored trust signal. camelCase wire form, like /report.
         */
        get: operations["get_trust_api_v1_trust_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available benchmark run ids (newest first).
         * @description Return the run ids under ``<REPORTS_ROOT>/benchmark/`` (newest first).
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The latest run's report (the BenchReport contract).
         * @description Return the newest run's validated :class:`BenchReport`.
         */
        get: operations["get_latest_report_api_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/report/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A specific run's report by id.
         * @description Return the validated :class:`BenchReport` for the given *run_id*.
         */
        get: operations["get_report_api_report__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The latest run's verification ledger (trust block + inference).
         * @description Latest run's verification ledger slice (trust block + inference).
         *
         *     The downloadable 'verification ledger' the UI links to for reviewers. The full
         *     V&V detail (wires, NIST datasets, nested-adequacy, σ-calibration, speed-significance)
         *     lives here rather than as a dedicated UI page; the landing carries only a compact,
         *     externally-anchored trust signal. camelCase wire form, like /report.
         */
        get: operations["get_trust_api_trust_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccuracyDist
         * @description Per-solver reduced-χ² distribution over repetitions.
         */
        AccuracyDist: {
            /** Raw */
            raw: number[];
            /** Median */
            median: number;
            /** P5 */
            p5: number;
            /** P25 */
            p25: number;
            /** P75 */
            p75: number;
        };
        /**
         * BackendProfile
         * @description All of ONE backend's featured-case metrics, grouped (no parallel dicts).
         *
         *     Element types match the per-panel charts exactly: `scaling`/`ecdf_*` keep the
         *     (x, y) `Point2D` axes, `param_err` is per-parameter, `param_spread`/`stability`
         *     keep the mean±sd `SpreadPt` bands.
         */
        BackendProfile: {
            fit: components["schemas"]["SolverFit"];
            /** Conv */
            conv: number[];
            /** Grad */
            grad: number[];
            /**
             * Conveff
             * @description Per-iteration convergence efficiency (cost reduction per step) derived from `conv`. Populated ONLY when `history_source == 'real'` (the subject's measured cost history); `None` for backends whose history is `reconstructed`, since a proxy-derived efficiency must not be presented as a measured series. Additive field — old payloads validate with None.
             */
            convEff?: number[] | null;
            /**
             * Historysource
             * @enum {string}
             */
            historySource: "real" | "reconstructed";
            timing: components["schemas"]["TimingDist"];
            accuracy: components["schemas"]["AccuracyDist"];
            summary: components["schemas"]["Summary"];
            /** Paramerr */
            paramErr: number[];
            /** Ecdfresid */
            ecdfResid: components["schemas"]["Point2D"][];
            /** Ecdftime */
            ecdfTime: components["schemas"]["Point2D"][];
            warmup: components["schemas"]["Warmup"];
            /** Scaling */
            scaling: components["schemas"]["Point2D"][];
            uncertainty: components["schemas"]["Uncertainty"];
            /** Paramspread */
            paramSpread: components["schemas"]["SpreadPt"][];
            stability: components["schemas"]["StabilityEntry"];
            /**
             * Jacobianconditionnumber
             * @description κ(J) at convergence. Structural property of the case, not the solver. κ ≥ 1e6 → ill-conditioned (explains backend disagreement); κ ≤ 1e4 → well-posed.
             */
            jacobianConditionNumber?: number | null;
            /**
             * Thetadistance
             * @description Scale-normalized per-iteration distance of the parameter vector to the synthetic ground truth, dₖ = ‖(θₖ − θ_true)/s‖₂ (s = per-parameter magnitude scale). Same length as `conv`. The REAL convergence-to-truth metric — distinct from the χ² descent in `conv`. None for non-synthetic cases (no θ_true) or backends without a parameter trajectory (only spectrafit's faer LM records it). Additive field — old payloads validate with None.
             */
            thetaDistance?: number[] | null;
        };
        /**
         * BenchReport
         * @description The complete benchmark report payload (the ``BENCH`` object consumed by the web app).
         */
        BenchReport: {
            /**
             * Schemaversion
             * @default 1.7
             */
            schemaVersion: string;
            /** Solvers */
            solvers: components["schemas"]["SolverMeta"][];
            /** Categories */
            categories: components["schemas"]["CategoryMeta"][];
            /** Analyzed */
            analyzed: components["schemas"]["Featured"][];
            /** Suite */
            suite: components["schemas"]["SuiteCase"][];
            /**
             * Baselinesolverid
             * @default lmfit
             */
            baselineSolverId: string;
            manifest?: components["schemas"]["ManifestSignals"] | null;
            /** @description V&V evidence block emitted by oracles.audit.runner. Additive — Pydantic fills None for pre-Plan-E payloads, so old runs still parse. */
            trustBlock?: components["schemas"]["TrustBlock"] | null;
            /** Panels */
            panels?: components["schemas"]["PanelSpec"][];
            inference?: components["schemas"]["InferenceBlock"] | null;
            /**
             * Gitcommit
             * @description Git commit hash (short, ≥7 chars) at benchmark run time. None when git is unavailable or the run is not in a git repo. Additive field — old payloads validate with None.
             */
            gitCommit?: string | null;
            /**
             * Gitbranch
             * @description Git branch name at benchmark run time. None when git is unavailable. Additive field.
             */
            gitBranch?: string | null;
            /**
             * Runtimestampunix
             * @description Unix epoch seconds when the benchmark run started (int). None when not captured. Additive field.
             */
            runTimestampUnix?: number | null;
        };
        /**
         * CI
         * @description A point estimate with its confidence interval.
         */
        CI: {
            /** Lo */
            lo: number;
            /** Point */
            point: number;
            /** Hi */
            hi: number;
        };
        /**
         * CalibrationResult
         * @description Frozen contract view of ``oracles.inference.CalibrationStat``.
         *
         *     Result of a binomial calibration test on parameter pulls
         *     (θ_est − θ_true) / σ_est. All fields mirror ``CalibrationStat`` exactly
         *     so the engine can pass the stat object straight into ``model_validate``.
         *
         *     When fewer than ``InferenceConfig.min_pulls`` pulls were collected, the
         *     engine still emits a **populated** record with ``skipped=True, passed=False,
         *     coverage=0.0, binomial_p=1.0`` — it is never ``None`` for insufficient data.
         *     ``None`` on ``InferenceBlock`` only appears for old payloads that predate
         *     the field (additive-minor schema upgrade); the web layer must check
         *     ``skipped`` to distinguish "test ran but data was insufficient" from
         *     "old payload that never had the field".
         *
         *     ``binomial_p`` is retained as an *honest strict diagnostic*: it reports the
         *     point-null test of H0: coverage = nominal.  At large n this has extreme power
         *     and will reject even a negligible deviation; it is NOT the gate criterion.
         *
         *     ``passed`` uses a practical-equivalence rule: the Clopper–Pearson CI must lie
         *     entirely within ``[nominal − equivalence_margin, nominal + equivalence_margin]``.
         *     ``equivalence_margin`` carries the pre-registered band (default 0.03 = ±3 pp).
         *     Additive field — old payloads without it default to 0.03 (matching the engine
         *     default) so validation is lossless.
         */
        CalibrationResult: {
            /** N */
            n: number;
            /** Coverage */
            coverage: number;
            /** Coveragecilo */
            coverageCiLo: number;
            /** Coveragecihi */
            coverageCiHi: number;
            /** Nominal */
            nominal: number;
            /** Binomialp */
            binomialP: number;
            /** Ksstat */
            ksStat: number;
            /** Ksp */
            ksP: number;
            /** Alpha */
            alpha: number;
            /**
             * Equivalencemargin
             * @default 0.03
             */
            equivalenceMargin: number;
            /** Passed */
            passed: boolean;
            /** Skipped */
            skipped: boolean;
        };
        /**
         * CaseInference
         * @description Per-case inference: intervals that make each comparison falsifiable.
         */
        CaseInference: {
            /** Caseid */
            caseId: string;
            speedupCi: components["schemas"]["CI"];
            deltaR2Ci: components["schemas"]["CI"];
        };
        /**
         * CategoryMeta
         * @description Benchmark category definition (id, label, case count, hue token).
         */
        CategoryMeta: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** N */
            n: number;
            /** Hue */
            hue: string;
        };
        /**
         * CredibilityRung
         * @description V&V maturity ladder (inspired by ASME V&V credibility levels).
         *
         *     The live wire set earns RUNG_2..RUNG_4. RUNG_1 / RUNG_5 are reserved
         *     end-stops (see the per-member comments), part of the public contract and
         *     pinned by an enum-value test — reserved, not dead.
         * @enum {integer}
         */
        CredibilityRung: 1 | 2 | 3 | 4 | 5;
        /**
         * EquivalenceResult
         * @description Per-category TOST: 'saturated' earned, not asserted.
         */
        EquivalenceResult: {
            /** Category */
            category: string;
            /** Equivalent */
            equivalent: boolean;
            /** Margin */
            margin: number;
            /** Diff */
            diff: number;
        };
        /**
         * ExprEdge
         * @description One tied/shared-parameter expression edge.
         *
         *     Wire form (camelCase): ``{"targetNode": "p1", "targetParam": "sigma",
         *     "expression": "p0.sigma"}``. Typed (not a bare ``dict[str, str]``) so the
         *     inner keys camelize like every other contract field — the web reads
         *     ``edge.targetNode`` / ``edge.targetParam``. Accepts the engine's snake_case
         *     dicts via ``populate_by_name`` on :class:`_Base`.
         */
        ExprEdge: {
            /** Targetnode */
            targetNode: string;
            /** Targetparam */
            targetParam: string;
            /** Expression */
            expression: string;
        };
        /**
         * Featured
         * @description One analyzed case rendered in full detail across all panels.
         *
         *     Per-backend metrics live in one `profiles` map (keyed by solver id); the
         *     remaining fields are case-level (shared across backends). A report carries a
         *     *list* of these (``BenchReport.analyzed``), one per deep-dived case, selectable
         *     in the UI; the `id` is unique within the list.
         */
        Featured: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** X */
            x: number[];
            /** Ref */
            ref: number[];
            /** Guess */
            guess: number[];
            /** Truth */
            truth: components["schemas"]["PeakACS"][];
            /** Guessparams */
            guessParams?: components["schemas"]["PeakACS"][];
            /** Noise */
            noise: number;
            /** Baseline */
            baseline: number;
            /** Profiles */
            profiles: {
                [key: string]: components["schemas"]["BackendProfile"];
            };
            /** Peaks */
            peaks: components["schemas"]["Peak"][];
            /** Paramnames */
            paramNames: string[];
            /** Corr */
            corr: number[][];
            /** Ngrid */
            Ngrid: number[];
            /** Schedule */
            schedule: number[];
            /** Runssched */
            runsSched: number[];
            /** Crossn */
            crossN: number;
            multidim?: components["schemas"]["MultiDim"] | null;
            globalFit?: components["schemas"]["GlobalFit"] | null;
            /** @description Nested-model adequacy V&V result for this case. Populated when the benchmark engine runs the nested-order oracle (Task 4.3). None for cases without a known generative order or when the oracle was not executed. Additive-minor field — old payloads without nestedAdequacy validate with None. */
            nestedAdequacy?: components["schemas"]["NestedAdequacy"] | null;
            /**
             * Modelsourcefile
             * @description Relative path to the Rust kernel source for this case's model, e.g. "crates/spectrafit-models/src/gaussian.rs". None for landscape/optfn cases without a dedicated kernel. Additive field — old payloads validate with None.
             */
            modelSourceFile?: string | null;
            /**
             * Modelformula
             * @description LaTeX formula string for the featured case's model shape. Sourced from PeakModel.formula_latex in the oracle registry. None when no formula is registered. Additive field.
             */
            modelFormula?: string | null;
            /**
             * Fixedparams
             * @description Per-node fixed parameter names, e.g. {"p0": ["center"]} means node p0's center was held at its guess value during the fit. Empty for unconstrained cases. Additive-minor field — old payloads validate with {}.
             */
            fixedParams?: {
                [key: string]: string[];
            };
            /**
             * Expredges
             * @description Tied/shared-parameter expression edges (camelCase keys on the wire: targetNode / targetParam / expression). Empty for unconstrained cases. Additive-minor field.
             */
            exprEdges?: components["schemas"]["ExprEdge"][];
        };
        /**
         * GlobalFit
         * @description Shared-model multi-spectrum joint global fit (the lmfit ``fit_multi_datasets`` pattern).
         *
         *     **SYNTHETIC placeholder — no experimental data.**  Uses a ``GlobalFitGraph``
         *     fit over synthetic Gaussian peaks; this field is NOT rendered in the production
         *     UI (classified ``ignored: cut``).  Peak centers/widths are shared across every
         *     dataset slice (global analysis) while each slice's amplitudes vary; ``traces``
         *     are the recovered per-peak amplitude traces and ``slices`` carry the per-dataset
         *     observed + jointly-fitted curves on the shared ``x`` grid.
         *
         *     The ``dataset_axis`` / ``axis_label`` names are deliberately axis-neutral: the
         *     global-fit machinery in spectrafit-core (``GlobalFitGraph``) is not specific to
         *     time — here the axis incidentally represents time, but the contract does not
         *     claim that.
         */
        GlobalFit: {
            /** X */
            x: number[];
            /** Datasetaxis */
            datasetAxis: number[];
            /** Slices */
            slices: components["schemas"]["GlobalFitSlice"][];
            /** Traces */
            traces: components["schemas"]["PeakTrace"][];
            /**
             * Source
             * @default spectrafit-core
             */
            source: string;
            /**
             * Xlabel
             * @default x
             */
            xLabel: string;
            /**
             * Axislabel
             * @default dataset
             */
            axisLabel: string;
            /**
             * Dataprovenance
             * @default synthetic
             * @enum {string}
             */
            dataProvenance: "measured" | "synthetic";
        };
        /**
         * GlobalFitSlice
         * @description One dataset slice in a shared-model multi-spectrum global fit: observed + jointly-fitted model.
         *
         *     The ``coord`` field carries the axis coordinate for this slice (e.g. a time
         *     value, a temperature, a sample index) — the name is axis-neutral because the
         *     global-fit machinery is not specific to time.
         */
        GlobalFitSlice: {
            /** Coord */
            coord: number;
            /** Obs */
            obs: number[];
            /** Model */
            model: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InferenceBlock
         * @description Top-level inference attached to BenchReport (additive 1.3 -> 1.4).
         *
         *     ``calibration`` and ``speed_inference`` are additive-minor fields (Task 5.3):
         *     old payloads that lack them validate with ``None``; the gate axis is inert
         *     when ``None`` (no-pass-by-absence rule).
         */
        InferenceBlock: {
            config: components["schemas"]["InferenceConfig"];
            /** Cases */
            cases: components["schemas"]["CaseInference"][];
            /** Equivalence */
            equivalence: components["schemas"]["EquivalenceResult"][];
            /** Winnerstability */
            winnerStability: {
                [key: string]: number;
            };
            calibration?: components["schemas"]["CalibrationResult"] | null;
            speedInference?: components["schemas"]["SpeedInferenceResult"] | null;
        };
        /**
         * InferenceConfig
         * @description Pre-registered inference parameters (written to the manifest, not tuned).
         *
         *     The four new fields are the Bonferroni-split family α values and the
         *     calibration-test hyper-parameters defined in the cycle 5 global constraints.
         *     They carry defaults so old payloads that lack them validate without a migrator.
         */
        InferenceConfig: {
            /** Equivalencemargin */
            equivalenceMargin: number;
            /** Bootstrapb */
            bootstrapB: number;
            /** Seed */
            seed: number;
            /** Fdrq */
            fdrQ: number;
            /**
             * Alphacalibration
             * @default 0.025
             */
            alphaCalibration: number;
            /**
             * Alphaspeed
             * @default 0.025
             */
            alphaSpeed: number;
            /**
             * Coveragenominal
             * @default 0.6827
             */
            coverageNominal: number;
            /**
             * Minpulls
             * @default 20
             */
            minPulls: number;
            /**
             * Calibrationmargin
             * @default 0.03
             */
            calibrationMargin: number;
        };
        /**
         * ManifestSignals
         * @description Headline numbers from ``manifest.json`` surfaced via the contract.
         *
         *     Mirrors the keys :func:`oracles.reports._headline` writes; ``pinned``
         *     is populated from :func:`oracles.reports.read_perf_baseline` (``None``
         *     when no baseline is currently pinned).
         */
        ManifestSignals: {
            /** Geomeanspeedupvsbaseline */
            geomeanSpeedupVsBaseline: number;
            /** Maxabsdeltar2 */
            maxAbsDeltaR2: number;
            /** Spectrafitwinrate */
            spectrafitWinRate: number;
            /** Regressions */
            regressions: number;
            pinned?: components["schemas"]["PinnedBaseline"] | null;
            /**
             * Harmonicmeanspeedupvsbaseline
             * @description Harmonic mean of per-case speedup values vs the baseline solver. Complements the geometric mean per Eeckhout (2024): the harmonic mean is the correct aggregate for equal-time comparisons and is always ≤ the geometric mean for positively-skewed speedup distributions. Additive field — old payloads on disk validate with None.
             */
            harmonicMeanSpeedupVsBaseline?: number | null;
            /**
             * Gatestate
             * @description Aggregate gate verdict. Single source of truth; the web UI must render this rather than recomputing from regression flags.
             */
            gateState?: ("pass" | "warn" | "fail") | null;
            /**
             * Nonfinitedr2Caseids
             * @description Case ids whose |Δr²| vs the baseline was non-finite (NaN/Inf). The accuracy gate fails when this is non-empty; carried as a list so _sanitize (which coerces non-finite floats) cannot erase the signal.
             */
            nonfiniteDr2CaseIds?: string[];
            /**
             * Saturatedcategories
             * @description Categories where every supported backend hits r²≥0.999 on every case. Differential below the noise floor; UI should mark these explicitly.
             */
            saturatedCategories?: string[];
            /**
             * Sanitizedvaluepaths
             * @description JSONPath-ish locators ('$.suite[3].m.jax.r2') of non-finite floats the presentation sanitizer coerced to 0.0 when this artifact was written. Non-empty means some rendered 0.0 values are suppressions, not measurements (G5 disclosure, 2026-06-23 tribunal). Carried as a list so _sanitize cannot erase the signal; additive field — old payloads validate with [].
             */
            sanitizedValuePaths?: string[];
        };
        /**
         * MultiDim
         * @description Genuinely N-dimensional (≥3-D) fit showcase (SP-2).
         *
         *     A synthetic N-D Gaussian is recovered by a real least-squares solve with the
         *     parametric ``gaussian_nd`` kernel (D inferred from the node's indexed
         *     ``center_<i>`` parameters). ``peaks`` are the *fitted* parameters and
         *     ``r_squared`` the recovery quality. Full N-D obs/model/residual grids are
         *     intentionally NOT stored — they do not scale past 2-D — so ``projections``
         *     carries 2-D marginal slices of the fitted model for any visualization.
         *
         *     **SYNTHETIC — no experimental data; NOT rendered in the production UI
         *     (classified ``ignored: cut``).**
         */
        MultiDim: {
            /** Ndims */
            nDims: number;
            /** Shape */
            shape: number[];
            /** Npoints */
            nPoints: number;
            /** Rsquared */
            rSquared: number;
            /** Peaks */
            peaks: components["schemas"]["NdPeak"][];
            /** Projections */
            projections: components["schemas"]["Projection"][];
            /**
             * Source
             * @default spectrafit-core
             */
            source: string;
            /**
             * Dataprovenance
             * @default synthetic
             * @enum {string}
             */
            dataProvenance: "measured" | "synthetic";
        };
        /**
         * NdPeak
         * @description A recovered N-D Gaussian peak: amplitude + per-axis center and sigma.
         *
         *     ``center`` and ``sigma`` each have ``n_dims`` entries (indexed `center_0..` /
         *     `sigma_0..` from the parametric ``gaussian_nd`` kernel).
         */
        NdPeak: {
            /** Amplitude */
            amplitude: number;
            /** Center */
            center: number[];
            /** Sigma */
            sigma: number[];
        };
        /**
         * NestedAdequacy
         * @description Frozen contract view of ``oracles.nested.NestedAdequacy``.
         *
         *     Result of a nested-order V&V against a known generative order: checks
         *     that model-selection criteria (LRT / F / AIC / BIC) recover the true
         *     order m* by comparing the (m*−1) reduced, m* true, and (m*+1)
         *     over-fitted models.
         *
         *     Both AIC and BIC verdicts are reported separately.  On the featured
         *     real tri-Gaussian, AIC over-selects the 4-peak model
         *     (``over_not_preferred_aic = False``) while BIC correctly recovers the
         *     true 3-peak order (``over_not_preferred_bic = True``).
         *
         *     ``nested_adequacy: NestedAdequacy | None = None`` on ``Featured`` is an
         *     additive-minor field — old payloads that lack it validate with ``None``.
         */
        NestedAdequacy: {
            /** Trueorder */
            trueOrder: number;
            /** Reducedrejected */
            reducedRejected: boolean;
            /** Overnotpreferredaic */
            overNotPreferredAic: boolean;
            /** Overnotpreferredbic */
            overNotPreferredBic: boolean;
            /** Selectedorderaic */
            selectedOrderAic: number;
            /** Selectedorderbic */
            selectedOrderBic: number;
            /** Recoveredtrueorderaic */
            recoveredTrueOrderAic: boolean;
            /** Recoveredtrueorderbic */
            recoveredTrueOrderBic: boolean;
            reducedVsTrue: components["schemas"]["SelectionStats"];
            trueVsOver: components["schemas"]["SelectionStats"];
        };
        /**
         * NistDataset
         * @description Per-dataset NIST StRD certified-value validation result.
         */
        NistDataset: {
            /**
             * Name
             * @description StRD problem name, e.g. 'Gauss1'.
             */
            name: string;
            /**
             * Model
             * @description Human-readable model description.
             */
            model: string;
            /** Nparams */
            nParams: number;
            /** Params */
            params: components["schemas"]["NistParam"][];
            /**
             * Minsigfigs
             * @description Worst (minimum) per-parameter sig-fig agreement.
             */
            minSigFigs: number;
            /**
             * Passed
             * @description True iff min_sig_figs ≥ the validation threshold.
             */
            passed: boolean;
        };
        /**
         * NistParam
         * @description One parameter's certified-vs-fitted agreement for a NIST StRD dataset.
         */
        NistParam: {
            /**
             * Name
             * @description NIST parameter name, e.g. 'b1'.
             */
            name: string;
            /**
             * Certified
             * @description NIST certified value (10+ sig figs).
             */
            certified: number;
            /**
             * Fitted
             * @description Spectrafit recovered value.
             */
            fitted: number;
            /**
             * Sigfigsagreed
             * @description -log10(|fitted-certified|/|certified|); ∞-capped for exact agreement.
             */
            sigFigsAgreed: number;
        };
        /**
         * NistValidation
         * @description Aggregate NIST StRD certified-value validation (the W8 evidence block).
         *
         *     Independent external replication against NIST's extended-precision certified
         *     values — the evidence RUNG_5 was reserved for. Additive on TrustBlock.
         */
        NistValidation: {
            /**
             * Thresholdsigfigs
             * @description Required minimum significant-figure agreement.
             */
            thresholdSigFigs: number;
            /** Datasets */
            datasets: components["schemas"]["NistDataset"][];
            /**
             * Minsigfigs
             * @description Worst min_sig_figs across all datasets.
             */
            minSigFigs: number;
            /**
             * Passed
             * @description True iff every dataset agrees to ≥ threshold sig figs.
             */
            passed: boolean;
            /**
             * Totalavailable
             * @description Size of the external NIST StRD nonlinear-regression universe (the denominator for 'N of M' coverage). Emitted by the validation builder so the UI never hardcodes the total. Additive — None for payloads written before this field existed.
             */
            totalAvailable?: number | null;
        };
        /**
         * PanelLayout
         * @description Grid sizing intent for one panel — hints, not CSS.
         */
        PanelLayout: {
            /**
             * Wide
             * @default false
             */
            wide: boolean;
            /**
             * Height
             * @default 230
             */
            height: number;
        };
        /**
         * PanelSpec
         * @description One report panel as data: which series, which chart, which slot.
         *
         *     The web app renders these generically (PanelRenderer); adding a panel is
         *     one record in ``oracles.panels.DEFAULT_PANELS``, not a new React block.
         *     ``source`` keys into the web-side series-builder registry — it is a contract
         *     string, pinned both sides by the default-panels fixture test.
         *     Additive 1.2 -> 1.3 bump together with ``BenchReport.panels``.
         */
        PanelSpec: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Desc
             * @default
             */
            desc: string;
            /**
             * Chartkind
             * @enum {string}
             */
            chartKind: "line" | "scatter" | "ecdf" | "violin" | "box" | "heatmap" | "field" | "lollipop" | "dumbbell" | "sparkline" | "band";
            /** Source */
            source: string;
            layout?: components["schemas"]["PanelLayout"];
        };
        /**
         * Peak
         * @description A single peak contribution curve (featured solver), labeled g1/g2/….
         */
        Peak: {
            /** Label */
            label: string;
            /** Y */
            y: number[];
        };
        /**
         * PeakACS
         * @description Peak parameters in the report's short form: amplitude / center / sigma.
         */
        PeakACS: {
            /** A */
            a: number;
            /** C */
            c: number;
            /** S */
            s: number;
        };
        /**
         * PeakTrace
         * @description A shared peak's amplitude evolving across the dataset axis.
         */
        PeakTrace: {
            /** Label */
            label: string;
            /** Center */
            center: number;
            /** Sigma */
            sigma: number;
            /** Amplitude */
            amplitude: number[];
        };
        /**
         * PinnedBaseline
         * @description The ``.spectrafit_reports/perf_baseline.json`` sidecar surfaced to the web.
         *
         *     Mirrors :func:`oracles.reports.write_perf_baseline`'s on-disk shape so
         *     the gate's self-vs-self signal is one fetch away in the browser.
         */
        PinnedBaseline: {
            /** Runid */
            runId: string;
            /** Recordedat */
            recordedAt: string;
            /** Geomeanspeedupvsbaseline */
            geomeanSpeedupVsBaseline: number;
            /** Ncases */
            nCases: number;
        };
        /**
         * Point2D
         * @description A single (x, y) point used by line / ecdf / scaling / warmup series.
         */
        Point2D: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * Projection
         * @description A 2-D projection (marginal slice) of a higher-D fit: axis-pair + matrix.
         */
        Projection: {
            /** Labels */
            labels: [
                string,
                string
            ];
            /** Matrix */
            matrix: number[][];
        };
        /**
         * SelectionStats
         * @description Frozen contract view of ``oracles.nested.SelectionStats``.
         *
         *     Statistics for one nested-model comparison (full minus reduced):
         *     LRT / F-test / information criteria.  All statistics are "full minus
         *     reduced" oriented: negative Δ-AIC / Δ-BIC means the full model is
         *     preferred.
         */
        SelectionStats: {
            /** Lrtstat */
            lrtStat: number;
            /** Lrtp */
            lrtP: number;
            /** Fstat */
            fStat: number;
            /** Fp */
            fP: number;
            /** Daic */
            dAIC: number;
            /** Dbic */
            dBIC: number;
        };
        /**
         * SolverFit
         * @description One solver's fit of the featured case: params + curve + residuals.
         */
        SolverFit: {
            /** Params */
            params: components["schemas"]["PeakACS"][];
            /** Curve */
            curve: number[];
            /** Resid */
            resid: number[];
        };
        /**
         * SolverMeta
         * @description Solver legend entry (id, label, and theme color tokens).
         *
         *     Re-exported from oracles.bench_contract for BenchReport.solvers.
         */
        SolverMeta: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Color */
            color: string;
            /** Soft */
            soft: string;
        };
        /**
         * SpeedInferenceResult
         * @description Frozen contract view of ``oracles.inference.SpeedStat``.
         *
         *     Result of a geomean-speedup significance test: bootstrap CI on the
         *     geometric mean of per-case speedup ratios plus sign-test and Wilcoxon
         *     signed-rank p-values. All fields mirror ``SpeedStat`` exactly.
         *
         *     When fewer than 2 valid per-case speedups were available, the engine still
         *     emits a **populated** record with ``skipped=True, passed=False,
         *     geomean_speedup=0.0, ci_lo=0.0, ci_hi=0.0`` — it is never ``None`` for
         *     insufficient data. ``None`` on ``InferenceBlock`` only appears for old
         *     payloads that predate the field (additive-minor schema upgrade); the web
         *     layer must check ``skipped`` to distinguish "test ran but data was
         *     insufficient" from "old payload that never had the field".
         */
        SpeedInferenceResult: {
            /** Geomeanspeedup */
            geomeanSpeedup: number;
            /** Cilo */
            ciLo: number;
            /** Cihi */
            ciHi: number;
            /** Excludesone */
            excludesOne: boolean;
            /** Signp */
            signP: number;
            /** Wilcoxonp */
            wilcoxonP: number;
            /** Alpha */
            alpha: number;
            /** Passed */
            passed: boolean;
            /** Skipped */
            skipped: boolean;
        };
        /**
         * SpreadPt
         * @description A mean±sd point versus run count (param-spread / stability series).
         */
        SpreadPt: {
            /** N */
            n: number;
            /** Mean */
            mean: number;
            /** Sd */
            sd: number;
        };
        /**
         * StabilityEntry
         * @description One backend's metric stability versus run count (mean±sd per metric).
         */
        StabilityEntry: {
            /** R2 */
            r2: components["schemas"]["SpreadPt"][];
            /** Rmse */
            rmse: components["schemas"]["SpreadPt"][];
            /** Redchi2 */
            redChi2: components["schemas"]["SpreadPt"][];
            /** Iters */
            iters: components["schemas"]["SpreadPt"][];
        };
        /**
         * SuiteCase
         * @description One row in the all-cases suite (regression map / win-rate tables).
         */
        SuiteCase: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Difficulty */
            difficulty: number;
            /** M */
            m: {
                [key: string]: components["schemas"]["SuiteMetric"];
            };
            /** Winner */
            winner: string;
            /** Regression */
            regression: boolean;
            /**
             * Winnerreason
             * @description Short human-readable explanation of WHY the winner won, contrasting key signals (κ(J), n_iter, convergence_efficiency) for the winner vs the baseline. None when the required signals are absent. Additive field — old payloads validate with None.
             */
            winnerReason?: string | null;
        };
        /**
         * SuiteMetric
         * @description Single-point per-solver metrics for a suite row.
         */
        SuiteMetric: {
            /** Speedup */
            speedup: number;
            /** R2 */
            r2: number;
            /** Redchi2 */
            redChi2: number;
            /** Medms */
            medMs: number;
            /** Paramerr */
            paramErr: number;
            /** Success */
            success: boolean;
            /**
             * Convergenceefficiency
             * @description Mean cost reduction per iteration: (cost₀ − costₙ) / n_iter. Populated when a real cost history exists (history_source=='real'); None for reconstructed histories. Additive field — old payloads validate with None.
             */
            convergenceEfficiency?: number | null;
            /**
             * Illconditioned
             * @description True when κ(J) ≥ 1e6 (ill-conditioned). None when κ(J) was not computed. Additive field.
             */
            illConditioned?: boolean | null;
            /**
             * Redchi2Weighted
             * @description σ-weighted reduced-χ²: Σ((y−ŷ)/σ)² / dof. None when σ=0 (noiseless case); see metric_undefined_reason. Additive field — old payloads validate with None.
             */
            redChi2Weighted?: number | null;
            /**
             * Metricundefinedreason
             * @description Human-readable explanation when red_chi2_weighted is None, e.g. "sigma=0 (noiseless)". Additive field.
             */
            metricUndefinedReason?: string | null;
        };
        /**
         * Summary
         * @description Headline KPI block per solver for the featured case.
         */
        Summary: {
            /** R2 */
            r2: number;
            /** Chi2 */
            chi2: number;
            /** Redchi2 */
            redChi2: number;
            /** Rmse */
            rmse: number;
            /** Mae */
            mae: number;
            /** Niter */
            nIter: number;
            /** Medms */
            medMs: number;
            /** Iqrms */
            iqrMs: number;
            /** Cv */
            cv: number;
            /** Speedup */
            speedup: number;
            /** Success */
            success: boolean;
            /** Aic */
            aic: number;
            /** Bic */
            bic: number;
            /** Daic */
            dAIC: number;
            /** Dbic */
            dBIC: number;
            speedupCi?: components["schemas"]["CI"] | null;
        };
        /**
         * TimingDist
         * @description Per-solver runtime distribution over timing repetitions (milliseconds).
         */
        TimingDist: {
            /** Raw */
            raw: number[];
            /** Median */
            median: number;
            /** Mean */
            mean: number;
            /** P5 */
            p5: number;
            /** P25 */
            p25: number;
            /** P75 */
            p75: number;
            /** P95 */
            p95: number;
            /** Iqr */
            iqr: number;
            /** Cv */
            cv: number;
        };
        /**
         * TrustBlock
         * @description Aggregate trust evidence attached to a BenchReport.
         */
        TrustBlock: {
            rung: components["schemas"]["CredibilityRung"];
            /** Wires */
            wires: components["schemas"]["WireResult"][];
            /** Nclaimsaudited */
            nClaimsAudited: number;
            /** Nclaimstotal */
            nClaimsTotal: number;
            /** @description NIST StRD certified-value validation (W8). Additive — Pydantic fills None for payloads that predate the A7 external-validation wire. */
            nistValidation?: components["schemas"]["NistValidation"] | null;
        };
        /**
         * Uncertainty
         * @description Parameter-pull diagnostics: pulls = (est−truth)/σ, coverage, reported σ.
         *
         *     ``coverage`` is ``None`` when no valid σ was available for any MC sample
         *     (e.g. backends like jax that set every ``param_stderr`` entry to ``None``).
         *     A ``None`` coverage is distinct from a genuine ``0.0`` (all pulls |p| ≥ 1σ).
         */
        Uncertainty: {
            /** Pulls */
            pulls: number[];
            /** Coverage */
            coverage: number | null;
            /** Sigma */
            sigma: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Warmup
         * @description Cold/hot amortization for one solver (JAX compile cost amortizing 1→100).
         */
        Warmup: {
            /** Curve */
            curve: components["schemas"]["Point2D"][];
            /** Pts */
            pts: components["schemas"]["WarmupPt"][];
            /** Hotthroughput */
            hotThroughput: number;
            /** Coldms */
            coldMs: number;
            /** Hotms */
            hotMs: number;
        };
        /**
         * WarmupPt
         * @description One cold/hot amortization point: per-run ms at a cumulative run count.
         */
        WarmupPt: {
            /** N */
            n: number;
            /** Perrun */
            perRun: number;
        };
        /**
         * WireResult
         * @description One verification wire's outcome.
         */
        WireResult: {
            /**
             * Wireid
             * @description W1..W6 from the value-stream diagram.
             */
            wireId: string;
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "warn" | "fail" | "skipped" | "gap";
            /**
             * Evidence
             * @description One-line evidence statement.
             */
            evidence: string;
            /** Details */
            details?: {
                [key: string]: number | string | boolean | null;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_latest_report_api_v1_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchReport"];
                };
            };
        };
    };
    get_report_api_v1_report__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trust_api_v1_trust_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_latest_report_api_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchReport"];
                };
            };
        };
    };
    get_report_api_report__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trust_api_trust_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
